spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: root123
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: BJ
        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center

  main:
    allow-bean-definition-overriding: true
server:
  port: 8010

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full

